# -----------------------------------------------------------
# ?? Gradle ???????? (?? 16GB ???????)
# -----------------------------------------------------------

# 1. Gradle ????????
# ???16G?????? 4g ? 5g ????? 8g ??? Android Studio ????????????
org.gradle.jvmargs=-Xmx5120m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8

# 2. ?????? (Gradle 3.0???????????)
org.gradle.daemon=true

# 3. ?????? (?? CPU ??)
org.gradle.parallel=true

# 4. ?????? (????????????????)
org.gradle.caching=true

# 5. ???? (??????????????? AS ???????? Configuration Cache?????)
org.gradle.configureondemand=true

# 6. Kotlin ????????
# ?????????2g-3g ???? 6g ???
kotlin.daemon.jvmargs=-Xmx3g

# -----------------------------------------------------------
# Android ???????? (?????????????)
# -----------------------------------------------------------

# ?? AndroidX ? (????????)
android.useAndroidX=true

# ?????? R ? (?????????????)
# ????????????????????????????????? false
android.nonTransitiveRClass=true

# ????
kotlin.code.style=official